[package]

name = "cgmath"
version = "0.1.5"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Tomasz Stachowiak",
        "Jarrett Colby"
]
license="Apache-2.0"
description="A linear algebra and mathematics library for computer graphics."
homepage="https://github.com/bjz/cgmath-rs"
repository="https://github.com/bjz/cgmath-rs"

[lib]
name = "cgmath"

[dependencies.rustc-serialize]
rustc_serialize = "*"

[dependencies]
num = "*"
rand = "*"
